version: 0.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - TRIPLET: x86-windows-static-winssl
    - TRIPLET: x64-windows-static-winssl
    - TRIPLET: x86-uwp
    - TRIPLET: x64-uwp
    - TRIPLET: arm-uwp
    - TRIPLET: arm-windows
    - TRIPLET: arm64-windows
    - TRIPLET: arm64-uwp
install:
- cmd: install.bat
build_script:
- cmd: >-
    echo ok

artifacts:
- path: '**\*.zip'
  name: Zip archive
- path: '**\*.nupkg'
  name: NuGet archive
