version: 0.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - TRIPLET: arm-windows
install:
- cmd: install.bat
build_script:
- cmd: >-
    echo ok
test: off
on_failure:
- cmd: type C:\projects\dependencies\vcpkg\buildtrees\libzip\install-arm-windows-dbg-out.log
artifacts:
- path: '**\*.zip'
  name: Zip archive
- path: '**\*.7z'
  name: 7Zip archive
- path: '**\*.nupkg'
  name: NuGet archive
