version: 0.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - TRIPLET: arm-windows
    - TRIPLET: x86-uwp
    - TRIPLET: x64-uwp
    - TRIPLET: arm-uwp
    - TRIPLET: arm64-windows
    - TRIPLET: arm64-uwp
    - TRIPLET: x86-windows-static-winssl
    - TRIPLET: x64-windows-static-winssl
install:
- cmd: install.bat
build_script:
- cmd: >-
    build.bat

    if errorlevel 1 (
        echo failed with %errorlevel%
        exit /b 0
    )

    package.bat
test: off
artifacts:
- path: '**\openrct2*.zip'
  name: Zip simplified archive
- path: '**\openrct2*.7z'
  name: 7z simplified archive
- path: '**\vcpkg*.zip'
  name: Zip vcpkg archive
- path: '**\vcpkg*.nupkg'
  name: NuGet vcpkg archive
- path: '**\*.log'
  name: Logs
