version: 0.1.0.{build}
os: Visual Studio 2017
cache:
- C:\vcpkg
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - TRIPLET: x86-windows-static
    - TRIPLET: x64-windows-static
install:
- cmd: install.bat
build_script:
- cmd: >-
    echo ok

artifacts:
- path: '**\*.zip'
  name: Zip archive
- path: '**\*.nupkg'
  name: NuGet archive
