name: CI
on: [push, pull_request]
env:
  VCPKG_COMMIT_HASH: 11ed79186fe850bd3a98cfbf1854514d2b3070a2
jobs:
  macos-package:
    name: macOS package universal library
    runs-on: macos-latest
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the version
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      # - name: Download All Artifacts
      #   uses: actions/download-artifact@v4
      #   with:
      #     pattern: openrct2-libs-v*-macos-dylibs.zip
      - name: Create Universal Library
        run: |
          wget -q https://github.com/janisozaur/Dependencies/releases/download/test-release-20240408/openrct2-libs-v-arm64-osx-openrct2-macos-dylibs.zip
          wget -q https://github.com/janisozaur/Dependencies/releases/download/test-release-20240408/openrct2-libs-v-x64-osx-openrct2-macos-dylibs.zip
          unzip -qo openrct2-libs-v${{ env.version }}-arm64-osx-openrct2-macos-dylibs.zip
          unzip -qo openrct2-libs-v${{ env.version }}-x64-osx-openrct2-macos-dylibs.zip
          ./macos_build.sh
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: openrct2-libs-v${{ env.version }}-universal-macos-dylibs.zip
          path: openrct2-libs-v${{ env.version }}-universal-macos-dylibs.zip
      - name: Load Release URL File from release job
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v4
        with:
          name: release_url
      - name: Get Release File Name & Upload URL
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_release_info
        shell: bash
        run: |
          value=`cat release_url.txt`
          echo "upload_url=$value" >> $GITHUB_OUTPUT
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: openrct2-libs-v${{ env.version }}-universal-macos-dylibs.zip
          asset_name: openrct2-libs-v${{ env.version }}-universal-macos-dylibs.zip
          asset_content_type: application/zip
